# Generated by Django 5.0.6 on 2026-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('building', models.CharField(max_length=120)),
                ('floor', models.CharField(blank=True, max_length=16)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('LECTURE', 'Lecture Room'), ('LAB', 'Laboratory'), ('COMPUTER_LAB', 'Computer Lab'), ('SEMINAR', 'Seminar Room'), ('AUDITORIUM', 'Auditorium')], default='LECTURE', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='rooms', to='facilities.equipment')),
            ],
            options={
                'ordering': ['building', 'code'],
                'indexes': [models.Index(fields=['room_type'], name='facilities__room_ty_d8d3a0_idx'), models.Index(fields=['capacity'], name='facilities__capacit_d6bd6a_idx')],
            },
        ),
    ]
