# Generated by Django 5.0.6 on 2026-06-17 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=32, unique=True)),
                ('rank', models.CharField(choices=[('LECTURER', 'Lecturer'), ('HOD', 'Head of Department'), ('DEAN', 'Dean'), ('LAB_ASSISTANT', 'Lab Assistant')], default='LECTURER', max_length=16)),
                ('title', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_no'],
            },
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.semester')),
                ('student_groups', models.ManyToManyField(related_name='allocations', to='academics.studentgroup')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='staff.lecturer')),
            ],
            options={
                'unique_together': {('lecturer', 'course', 'semester')},
            },
        ),
    ]
