# Generated by Django 5.0.6 on 2026-06-17 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deans_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.programme'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='academics.programme'),
        ),
        migrations.AddField(
            model_name='term',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='academics_c_code_21c5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['year_of_study'], name='academics_c_year_of_55518d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('programme', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('programme', 'name', 'year_of_study')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('semester', 'number')},
        ),
    ]
