# Generated by Django 5.0.6 on 2026-06-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_departments', to='staff.lecturer'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='academics.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.programme'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='academics.programme'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='term',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('semester', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'programme', 'semester', 'term')},
        ),
    ]
