/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStudentGroupsRouteImport } from './routes/_app.student-groups'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSemestersRouteImport } from './routes/_app.semesters'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppProgrammesRouteImport } from './routes/_app.programmes'
import { Route as AppLecturersRouteImport } from './routes/_app.lecturers'
import { Route as AppFacultiesRouteImport } from './routes/_app.faculties'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppTimetablesIndexRouteImport } from './routes/_app.timetables.index'
import { Route as AppTimetablesGenerateRouteImport } from './routes/_app.timetables.generate'
import { Route as AppTimetablesIdRouteImport } from './routes/_app.timetables.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentGroupsRoute = AppStudentGroupsRouteImport.update({
  id: '/student-groups',
  path: '/student-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSemestersRoute = AppSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppProgrammesRoute = AppProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AppRoute,
} as any)
const AppLecturersRoute = AppLecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultiesRoute = AppFacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetablesIndexRoute = AppTimetablesIndexRouteImport.update({
  id: '/timetables/',
  path: '/timetables/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetablesGenerateRoute = AppTimetablesGenerateRouteImport.update({
  id: '/timetables/generate',
  path: '/timetables/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetablesIdRoute = AppTimetablesIdRouteImport.update({
  id: '/timetables/$id',
  path: '/timetables/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/courses': typeof AppCoursesRoute
  '/departments': typeof AppDepartmentsRoute
  '/faculties': typeof AppFacultiesRoute
  '/lecturers': typeof AppLecturersRoute
  '/programmes': typeof AppProgrammesRoute
  '/rooms': typeof AppRoomsRoute
  '/semesters': typeof AppSemestersRoute
  '/settings': typeof AppSettingsRoute
  '/student-groups': typeof AppStudentGroupsRoute
  '/timetables/$id': typeof AppTimetablesIdRoute
  '/timetables/generate': typeof AppTimetablesGenerateRoute
  '/timetables/': typeof AppTimetablesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/courses': typeof AppCoursesRoute
  '/departments': typeof AppDepartmentsRoute
  '/faculties': typeof AppFacultiesRoute
  '/lecturers': typeof AppLecturersRoute
  '/programmes': typeof AppProgrammesRoute
  '/rooms': typeof AppRoomsRoute
  '/semesters': typeof AppSemestersRoute
  '/settings': typeof AppSettingsRoute
  '/student-groups': typeof AppStudentGroupsRoute
  '/': typeof AppIndexRoute
  '/timetables/$id': typeof AppTimetablesIdRoute
  '/timetables/generate': typeof AppTimetablesGenerateRoute
  '/timetables': typeof AppTimetablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/faculties': typeof AppFacultiesRoute
  '/_app/lecturers': typeof AppLecturersRoute
  '/_app/programmes': typeof AppProgrammesRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/semesters': typeof AppSemestersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/student-groups': typeof AppStudentGroupsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/timetables/$id': typeof AppTimetablesIdRoute
  '/_app/timetables/generate': typeof AppTimetablesGenerateRoute
  '/_app/timetables/': typeof AppTimetablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/courses'
    | '/departments'
    | '/faculties'
    | '/lecturers'
    | '/programmes'
    | '/rooms'
    | '/semesters'
    | '/settings'
    | '/student-groups'
    | '/timetables/$id'
    | '/timetables/generate'
    | '/timetables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/courses'
    | '/departments'
    | '/faculties'
    | '/lecturers'
    | '/programmes'
    | '/rooms'
    | '/semesters'
    | '/settings'
    | '/student-groups'
    | '/'
    | '/timetables/$id'
    | '/timetables/generate'
    | '/timetables'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/courses'
    | '/_app/departments'
    | '/_app/faculties'
    | '/_app/lecturers'
    | '/_app/programmes'
    | '/_app/rooms'
    | '/_app/semesters'
    | '/_app/settings'
    | '/_app/student-groups'
    | '/_app/'
    | '/_app/timetables/$id'
    | '/_app/timetables/generate'
    | '/_app/timetables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-groups': {
      id: '/_app/student-groups'
      path: '/student-groups'
      fullPath: '/student-groups'
      preLoaderRoute: typeof AppStudentGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/semesters': {
      id: '/_app/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof AppSemestersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programmes': {
      id: '/_app/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof AppProgrammesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lecturers': {
      id: '/_app/lecturers'
      path: '/lecturers'
      fullPath: '/lecturers'
      preLoaderRoute: typeof AppLecturersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faculties': {
      id: '/_app/faculties'
      path: '/faculties'
      fullPath: '/faculties'
      preLoaderRoute: typeof AppFacultiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetables/': {
      id: '/_app/timetables/'
      path: '/timetables'
      fullPath: '/timetables/'
      preLoaderRoute: typeof AppTimetablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetables/generate': {
      id: '/_app/timetables/generate'
      path: '/timetables/generate'
      fullPath: '/timetables/generate'
      preLoaderRoute: typeof AppTimetablesGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetables/$id': {
      id: '/_app/timetables/$id'
      path: '/timetables/$id'
      fullPath: '/timetables/$id'
      preLoaderRoute: typeof AppTimetablesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppFacultiesRoute: typeof AppFacultiesRoute
  AppLecturersRoute: typeof AppLecturersRoute
  AppProgrammesRoute: typeof AppProgrammesRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSemestersRoute: typeof AppSemestersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentGroupsRoute: typeof AppStudentGroupsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTimetablesIdRoute: typeof AppTimetablesIdRoute
  AppTimetablesGenerateRoute: typeof AppTimetablesGenerateRoute
  AppTimetablesIndexRoute: typeof AppTimetablesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppFacultiesRoute: AppFacultiesRoute,
  AppLecturersRoute: AppLecturersRoute,
  AppProgrammesRoute: AppProgrammesRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSemestersRoute: AppSemestersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentGroupsRoute: AppStudentGroupsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTimetablesIdRoute: AppTimetablesIdRoute,
  AppTimetablesGenerateRoute: AppTimetablesGenerateRoute,
  AppTimetablesIndexRoute: AppTimetablesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
